# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import Excel_func
import ble_func

import serial
import threading

import os


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label_Excel = QtWidgets.QLabel(self.centralwidget)
        self.label_Excel.setGeometry(QtCore.QRect(50, 50, 50, 50))
        self.label_Excel.setObjectName("label_Excel")

        self.label_HiCardiList = QtWidgets.QLabel(self.centralwidget)
        self.label_HiCardiList.setGeometry(QtCore.QRect(900, 50, 100, 50))
        self.label_HiCardiList.setObjectName("label_HiCardiList")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(775, 250, 100, 100))
        self.pushButton.setObjectName("btn_Connect")

        self.pushButton.clicked.connect((self.select_and_connect))

        self.Widget_Excel = QtWidgets.QTableWidget(self.centralwidget)      #엑셀 테이블 위젯
        self.Widget_Excel.setGeometry(QtCore.QRect(50, 100, 700, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Widget_Excel.sizePolicy().hasHeightForWidth())
        self.Widget_Excel.setSizePolicy(sizePolicy)
        self.Widget_Excel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Widget_Excel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Widget_Excel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Widget_Excel.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Widget_Excel.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Widget_Excel.setAlternatingRowColors(True)
        self.Widget_Excel.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Widget_Excel.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Widget_Excel.setShowGrid(True)
        self.Widget_Excel.setGridStyle(QtCore.Qt.SolidLine)
        self.Widget_Excel.setWordWrap(True)
        self.Widget_Excel.setCornerButtonEnabled(False)
        self.Widget_Excel.setRowCount(100)
        self.Widget_Excel.setObjectName("Widget_Excel")
        self.Widget_Excel.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.Widget_Excel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Widget_Excel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Widget_Excel.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Widget_Excel.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Widget_Excel.setHorizontalHeaderItem(4, item)
        self.Widget_Excel.horizontalHeader().setCascadingSectionResizes(False)
        self.Widget_Excel.horizontalHeader().setSortIndicatorShown(True)
        self.Widget_Excel.horizontalHeader().setStretchLastSection(False)
        self.Widget_Excel.verticalHeader().setCascadingSectionResizes(False)
        self.Widget_Excel.verticalHeader().setHighlightSections(True)
        self.Widget_Excel.verticalHeader().setSortIndicatorShown(False)
        self.Widget_Excel.verticalHeader().setStretchLastSection(False)

        p_excel = self.Widget_Excel.palette()
        p_excel.setColor(p_excel.Inactive, p_excel.Highlight, p_excel.color(p_excel.Active, p_excel.Highlight))
        self.Widget_Excel.setPalette(p_excel)



        self.Widget_HiCardiList = QtWidgets.QTableWidget(self.centralwidget)
        self.Widget_HiCardiList.setGeometry(QtCore.QRect(900, 100, 350, 400))
        self.Widget_HiCardiList.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Widget_HiCardiList.setAlternatingRowColors(True)
        self.Widget_HiCardiList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Widget_HiCardiList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Widget_HiCardiList.setRowCount(100)
        self.Widget_HiCardiList.setObjectName("Widget_HiCardiList")
        self.Widget_HiCardiList.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.Widget_HiCardiList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Widget_HiCardiList.setHorizontalHeaderItem(1, item)

        p_scan = self.Widget_HiCardiList.palette()
        p_scan.setColor(p_scan.Inactive, p_scan.Highlight, p_scan.color(p_scan.Active, p_scan.Highlight))
        self.Widget_HiCardiList.setPalette(p_scan)



        self.btn_ExcelLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ExcelLoad.setGeometry(QtCore.QRect(100, 50, 100, 50))
        self.btn_ExcelLoad.setObjectName("btn_ExcelLoad")

        self.btn_ExcelLoad.clicked.connect(self.excelload)  # 엑셀 임시##########################################



        self.btn_Scan = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Scan.setGeometry(QtCore.QRect(1000, 50, 100, 50))
        self.btn_Scan.setObjectName("btn_Scan")

        self.btn_Scan.clicked.connect(self.scan)



        self.btn_ExcelSave = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ExcelSave.setGeometry(QtCore.QRect(200, 50, 100, 50))
        self.btn_ExcelSave.setObjectName("btn_ExcelSave")
        self.btn_ExcelSave.clicked.connect(self.excelsave)


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def excelload(self):

        sheet, excelfile, excelrow, excelcolumn, rows = Excel_func.init_excel()  # 엑셀 파일 생성

        all_values = []
        for q in rows:
            row_value = []
            for cell in q:
                row_value.append(cell.value)
            all_values.append(row_value)

        for i in range(excelrow):

            if (i > 0):
                for j in range(excelcolumn):

                    self.Widget_Excel.setItem(i - 1, j, QtWidgets.QTableWidgetItem(all_values[i][j]))


    def excelsave(self):    ##엑셀세이브 버튼 만들다가 중단

        WidgetCol = self.Widget_Excel.columnCount()
        WidgetRow = self.Widget_Excel.rowCount()

        WidgetData1 = []
        WidgetData2 = []

        for i in range(WidgetRow):
            for j in range(WidgetCol):
                if str(type(self.Widget_Excel.item(i,j))) == "<class 'PyQt5.QtWidgets.QTableWidgetItem'>":
                    WidgetData2.append((self.Widget_Excel.item(i,j).text()))

            if WidgetData2:
                WidgetData1.append(WidgetData2)
            WidgetData2 = []

        sheet.delete_rows(2,WidgetRow)

        for i in range(len(WidgetData1)):
            Excel_func.qrdata_write(sheet, WidgetData1[i])
            Excel_func.save_excel(excelfile)

    def scan(self):
        ble_func.list_scan.clear()
        ble_func.list_mac = []

        ble_func.scan(collector)

        count = len(ble_func.list_scan)

        for i in range(count):
            self.Widget_HiCardiList.setItem(i, 0,  QtWidgets.QTableWidgetItem(ble_func.list_scan[i]))
            self.Widget_HiCardiList.setItem(i, 1, QtWidgets.QTableWidgetItem(ble_func.list_mac[i]))


        # ble_func.list_scan =[]


        # ble_func.list_mac = []



    def select_and_connect(self):
        # print(self.Widget_Excel.currentRow())
        # print(self.Widget_Excel.currentColumn())
        # print(self.Widget_Excel.currentItem())
        count1 = len(self.Widget_Excel.selectedItems())
        list1 = []
        list1.extend(self.Widget_Excel.selectedItems())
        for i in range(count1):
            list1[i] = list1[i].text()

        count2 = len(self.Widget_HiCardiList.selectedItems())
        list2 = []
        list2.extend(self.Widget_HiCardiList.selectedItems())
        for i in range(count2):
            list2[i] =list2[i].text()

        HiCardi_name = list2[0]
        HiCardi_num = list1[2]
        HiCardi_num = int(HiCardi_num[1:5])

        ble_func.write(collector,HiCardi_name,HiCardi_num)

        ##시작
        mac_address = self.Widget_HiCardiList.selectedItems()
        self.Widget_Excel.setItem(self.Widget_Excel.currentRow(),3,QtWidgets.QTableWidgetItem(mac_address[1]))


        print('connect')
        # ble_func.list_scan.pop(a)
        # ble_func.list_mac.pop(a)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Excel.setText(_translate("MainWindow", "Excel"))
        self.label_HiCardiList.setText(_translate("MainWindow", "HiCardi List"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))
        self.Widget_Excel.setSortingEnabled(True)
        item = self.Widget_Excel.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Device Identifier"))
        item = self.Widget_Excel.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Manufacturing/Production Date"))

        item = self.Widget_Excel.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Serial Number"))
        item = self.Widget_Excel.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Mac address"))
        item = self.Widget_HiCardiList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Device"))
        item = self.Widget_HiCardiList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mac address"))
        self.btn_ExcelLoad.setText(_translate("MainWindow", "Excel Load"))
        self.btn_Scan.setText(_translate("MainWindow", "Scan"))
        self.btn_ExcelSave.setText(_translate("MainWindow", "Excel Save"))


def qrread():
    while True:
        data = Excel_func.qrdata_read(ser)
        Excel_func.qrdata_write(sheet, data)
        Excel_func.save_excel(excelfile)
        ui.btn_ExcelLoad.click()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sheet, excelfile, excelrow, excelcolumn, rows = Excel_func.init_excel()  # 엑셀 파일 생성
    ser = serial.Serial('COM5', 9600)   #serial 통신 바코드리더기
    collector = ble_func.init("NRF52", "COM6")
    ui.btn_ExcelLoad.click()


    qrthread = threading.Thread(target=qrread)   #바코드스레드로 돌림
    qrthread.start()


    #########ble코드 시작
    sys.exit(app.exec_())

